### Linear layer

In [1]:
import torch

#### Raw Linear Layer

$$\begin{gathered}
y=x\cdot{W}+b, \\
\text{where }x\in\mathbb{R}^{N\times{n}}\text{, }y\in\mathbb{R}^{N\times{m}}. \\
\\
\text{Thus, }W\in\mathbb{R}^{n\times{m}}\text{ and }b\in\mathbb{R}^m.
\end{gathered}$$

In [2]:
w = torch.FloatTensor([[1, 2], [3, 4], [5, 6]])
b = torch.FloatTensor([2, 2])

In [3]:
print(w.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [4]:
def linear(x, w, b):
    y = torch.matmul(x, w) + b

    return y

In [5]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(x.size())

torch.Size([4, 3])


In [6]:
y = linear(x, w, b) # (4, 3), (3, 2), (2, 2)

In [7]:
print(y.size())

torch.Size([4, 2])


### nn.Module

In [8]:
import torch.nn as nn

In [11]:
class MyLinear(nn.Module):

    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.w = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    
    # 내가 원하는대로 입력과 출력을 설계할 수 있다.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.w) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)

        return y

In [12]:
linear = MyLinear(3, 2)

y = linear(x)

In [13]:
print(y.size())

torch.Size([4, 2])


In [14]:
for p in linear.parameters():
    print(p)

You can see that there is no weight parameters to learn.
Above way can forward(or calculate) values, but it cannot be trained.

### nn.Parameters

In [20]:
class MyLinear(nn.Module):

    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.w = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    
    # 내가 원하는대로 입력과 출력을 설계할 수 있다.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.w) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)

        return y

In [21]:
linear = MyLinear(3, 2)

y = linear(x)

In [22]:
print(y.size())

torch.Size([4, 2])


In [23]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[-4.1121e+17,  4.5764e-41],
        [-4.1139e+17,  4.5764e-41],
        [-4.1303e+17,  4.5764e-41]], requires_grad=True)
Parameter containing:
tensor([-4.1121e+17,  4.5764e-41], requires_grad=True)


### nn.Linear

In [24]:
linear = nn.Linear(3, 2)

y = linear(x)

In [25]:
print(y.size())

torch.Size([4, 2])


In [26]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.1001, -0.4973,  0.0272],
        [ 0.4513, -0.2831, -0.4267]], requires_grad=True)
Parameter containing:
tensor([0.0750, 0.5025], requires_grad=True)


### nn.Module can contain other nn.Module's child classes.

In [30]:
class MyLinear(nn.Module):


    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.linear = nn.Linear(input_dim, output_dim)


    def forward(self, x):
        
        y = self.linear(x)

        return y

In [31]:
linear = MyLinear(3, 2)

y = linear(x)

In [32]:
print(y.size())

torch.Size([4, 2])


In [33]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.3005, -0.0477, -0.5367],
        [ 0.2245, -0.3160,  0.0326]], requires_grad=True)
Parameter containing:
tensor([-0.3676, -0.4603], requires_grad=True)
