### gradient descent

In [9]:
import torch
import torch.nn.functional as F

In [10]:
target = torch.FloatTensor([[.1, .2, .3], [.4, .5, .6], [.7, .8, .9]])

In [11]:
x = torch.rand_like(target)

x.requires_grad = True

print(x)

tensor([[0.7255, 0.7880, 0.3588],
        [0.0494, 0.6503, 0.9340],
        [0.3421, 0.0396, 0.5538]], requires_grad=True)


In [12]:
loss = F.mse_loss(x, target)

loss

tensor(0.2026, grad_fn=<MseLossBackward0>)

In [13]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1

    loss.backward()

    x = x - learning_rate * x.grad

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(target, x)

    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 1.2257e-01
tensor([[0.5865, 0.6573, 0.3457],
        [0.1273, 0.6169, 0.8598],
        [0.4216, 0.2086, 0.6307]], requires_grad=True)
2-th Loss: 7.4150e-02
tensor([[0.4784, 0.5557, 0.3355],
        [0.1879, 0.5909, 0.8021],
        [0.4835, 0.3400, 0.6906]], requires_grad=True)
3-th Loss: 4.4856e-02
tensor([[0.3943, 0.4766, 0.3276],
        [0.2351, 0.5707, 0.7572],
        [0.5316, 0.4422, 0.7371]], requires_grad=True)
4-th Loss: 2.7135e-02
tensor([[0.3289, 0.4152, 0.3215],
        [0.2717, 0.5550, 0.7222],
        [0.5690, 0.5217, 0.7733]], requires_grad=True)
5-th Loss: 1.6415e-02
tensor([[0.2780, 0.3673, 0.3167],
        [0.3002, 0.5428, 0.6951],
        [0.5981, 0.5836, 0.8015]], requires_grad=True)
6-th Loss: 9.9302e-03
tensor([[0.2385, 0.3302, 0.3130],
        [0.3224, 0.5333, 0.6739],
        [0.6208, 0.6317, 0.8234]], requires_grad=True)
7-th Loss: 6.0071e-03
tensor([[0.2077, 0.3012, 0.3101],
        [0.3396, 0.5259, 0.6575],
        [0.6384, 0.6691, 0.8404]], requi